name: Docker Image Register

on:
  pull_request:
    paths:
      - 'infra/*'

jobs:
  docker-image-register:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ucanlab
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push app Container (Development)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/php/Dockerfile
          push: true
          tags: ucanlab/laravel-boilerplate-app:development
          target: development

      - name: Build & Push app Container (Deploy)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/docker/php/Dockerfile
          push: true
          tags: ucanlab/laravel-boilerplate-app:latest
          target: deploy

      - name: Build & Push nginx Container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infra/docker/nginx/Dockerfile
          push: true
          tags: ucanlab/laravel-boilerplate-web:latest

      - name: Build & Push db Container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infra/docker/mysql/Dockerfile
          push: true
          tags: ucanlab/laravel-boilerplate-db:latest
