name: Laravel Testing

on:
  pull_request:

jobs:
  laravel-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Version
        run: docker version

      - name: Create & Start Docker Containers
        run: docker compose up -d

      - name: OS Version
        run: |
          docker compose exec app cat /etc/os-release
          docker compose exec app cat /etc/debian_version

      - name: PHP Version
        run: docker compose exec app php --version

      - name: Composer Version
        run: docker compose exec app composer --version

      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./src/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker compose exec app composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Laravel Version
        run: docker compose exec app php artisan --version

      - name: Laravel Settings
        run: docker compose exec app cp .env.example .env

      - name: Wait for the MySQL container to start
        run: sleep 5s
        shell: bash

      - name: Laravel Migrate Testing
        run: docker compose exec app php artisan migrate

      - name: Laravel Rollback Testing
        run: docker compose exec app php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: docker compose exec app php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker compose exec app php artisan test
